<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SignAssembly>false</SignAssembly>
    <RootNamespace>SampleWeb.Client</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BlazorQL" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
  </ItemGroup>
</Project>
